### PR TITLE
IPlugin::isActive refactoring

### PR DESCRIPTION
**Pull request by Holt59**
See https://github.com/ModOrganizer2/modorganizer-uibase/pull/100

### CODE REVIEW

**Comment by isanae** [comment]
I guess this should be a requirement for any active game plugin that returns something in `iniFiles()`. Is that possible?

**Comment by Holt59** [comment]
> 
> 
> I guess this should be a requirement for any active game plugin that returns something in `iniFiles()`. Is that possible?

It should be doable, although

**Comment by Holt59** [comment]
> 
> 
> I guess this should be a requirement for any active game plugin that returns something in `iniFiles()`. Is that possible?

Can do. What should the message be? Currently I have *"The current game plugin does not have associated settings file."*.

**Comment by isanae** [comment]
"The {game name} game plugin does not use INI files"?

**Comment by Holt59** [comment]
> 
> 
> "The {game name} game plugin does not use INI files"?

I'd rather not use INI files since it works for other type of files (and some basic game plugins use it). Settings files? Configuration files?

**Comment by isanae** [comment]
Meh, it's called INI Bakery. But sure, configuration files works.

**Pull request merged**
